# Generated by Django 4.2.27 on 2025-12-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='instructor_name',
            field=models.CharField(default='Expert Instructor', max_length=200),
        ),
        migrations.AddField(
            model_name='training',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='training',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='training',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='training',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=3),
        ),
        migrations.AddField(
            model_name='training',
            name='students_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='training',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='trainings/'),
        ),
        migrations.AlterField(
            model_name='training',
            name='mode',
            field=models.CharField(blank=True, help_text='e.g., Online, In-person, Hybrid', max_length=100),
        ),
    ]
