# Generated by Django 4.2.27 on 2025-12-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_training_discount_price_training_instructor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text',
            field=models.TextField(blank=True, default='We build dependable AI systems — research, productization, and production operations.'),
        ),
    ]
