# Generated by Django 4.2.27 on 2026-01-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_newslettersubscription_alter_blogpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
    ]
