# Generated by Django 4.2.27 on 2026-01-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_teammember_linkedin_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(blank=True, help_text='FontAwesome class, e.g., fas fa-microchip', max_length=80)),
                ('image', models.ImageField(blank=True, null=True, upload_to='values/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
