# Generated by Django 4.2.27 on 2026-01-06 10:52

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sitesettings_contact_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='category',
            field=models.CharField(default='General AI', max_length=100),
        ),
        migrations.AlterField(
            model_name='training',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Detailed Syllabus'),
        ),
    ]
