# Generated by Django 4.2.27 on 2026-01-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_training_category_alter_training_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.TextField(default='We architect intelligent ecosystems that think, learn, and execute. From agentic workflows to enterprise LLMs, we build the future of autonomy.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='Next-Gen AI Agents & Autonomous Systems', max_length=250),
        ),
    ]
