# Generated by Django 4.2.27 on 2026-01-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sitesettings_hero_subtitle_sitesettings_hero_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='industry',
            name='icon_class',
            field=models.CharField(default='fas fa-building', max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='icon_class',
            field=models.CharField(default='fas fa-box', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='what_we_do_desc',
            field=models.TextField(default='End-to-end services to help you adopt and scale artificial intelligence with cutting-edge technology.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='what_we_do_subtitle',
            field=models.CharField(default='What We Do', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='what_we_do_title',
            field=models.CharField(default='Comprehensive AI <span class="text-gradient">Solutions</span>', max_length=250),
        ),
    ]
