# Generated by Django 4.2.27 on 2026-01-06 15:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_industry_featured_industry_icon_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
