# Generated by Django 4.2.27 on 2026-01-07 07:33

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_jobopening_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchitem',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Detailed Research'),
        ),
        migrations.AddField(
            model_name='researchitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='researchitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='research/'),
        ),
        migrations.AddField(
            model_name='researchitem',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='researchitem',
            name='link',
            field=models.URLField(blank=True, help_text='Optional external link (e.g. ArXiv)'),
        ),
        migrations.AlterField(
            model_name='researchitem',
            name='summary',
            field=models.TextField(blank=True, help_text='Short description for the card'),
        ),
    ]
