# Generated by Django 6.0 on 2026-01-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_researchitem_content_researchitem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='features',
            field=models.TextField(default='Advanced Neural Networks\nVector DB Integration\nCompliance-first Design', help_text='Enter one feature per line'),
        ),
    ]
