# Generated by Django 6.0 on 2026-01-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_service_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='course_desc',
            field=models.TextField(default='Start your journey today with our most in-demand training programs.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='course_subtitle',
            field=models.CharField(default='Level Up', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='course_title',
            field=models.CharField(default='Most Popular <span class="text-gradient">Courses</span>', max_length=250),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ind_desc',
            field=models.TextField(default='Deploying autonomous intelligence across critical global infrastructures.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ind_subtitle',
            field=models.CharField(default='Sectors', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ind_title',
            field=models.CharField(default='Industries We <span class="text-gradient">Empower</span>', max_length=250),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='prod_subtitle',
            field=models.CharField(default='Innovation', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='prod_title',
            field=models.CharField(default='Proprietary <span class="text-gradient">Products</span>', max_length=250),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='proj_subtitle',
            field=models.CharField(default='Our Work', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='proj_title',
            field=models.CharField(default='Featured <span class="text-gradient">Projects</span>', max_length=250),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='test_subtitle',
            field=models.CharField(default='Testimonials', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='test_title',
            field=models.CharField(default='Trusted by <span class="text-gradient">Leaders</span>', max_length=250),
        ),
    ]
