# Generated by Django 4.2.27 on 2025-12-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_document_documentchunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gemini_api_key', models.CharField(help_text='Enter your Gemini API Key', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Only the most recently updated active config will be used')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chatbot Configuration',
                'verbose_name_plural': 'Chatbot Configuration',
            },
        ),
    ]
